// Generated by Tools/generate_paint_poisson.py. Do not edit the point tables.
// Two periodic Bridson sets: period 4, minimum separation 0.8 in density-scaled UV.
#ifndef PAINT_POISSON_POINTS_INCLUDED
#define PAINT_POISSON_POINTS_INCLUDED
#define PAINT_POISSON_SET0_SIZE 14
static const float2 PaintPoissonPoints0[14] = {
    float2(3.98548951, 3.53928039),
    float2(3.00280046, 3.53123054),
    float2(0.43634455, 0.53813345),
    float2(3.76831358, 2.75435701),
    float2(1.86252224, 0.40288124),
    float2(2.83068918, 1.85189880),
    float2(0.32921594, 1.55882013),
    float2(3.10654212, 0.57836615),
    float2(1.71115758, 1.31488080),
    float2(2.55606300, 2.63448806),
    float2(0.87802869, 3.09872659),
    float2(1.02747659, 1.96121394),
    float2(1.85606980, 3.05407723),
    float2(1.10512551, 0.04715131)
};

#define PAINT_POISSON_SET1_SIZE 14
static const float2 PaintPoissonPoints1[14] = {
    float2(2.54628882, 1.04374271),
    float2(3.03244265, 3.86703088),
    float2(2.06409877, 2.19635584),
    float2(1.88705671, 3.65940390),
    float2(3.68345062, 1.00786440),
    float2(0.35551786, 0.21227261),
    float2(0.54310303, 3.39966631),
    float2(3.13139451, 1.74765418),
    float2(3.31245100, 3.07326390),
    float2(1.25287252, 2.71126173),
    float2(0.20097295, 1.85890078),
    float2(1.30679966, 0.40168215),
    float2(1.37483292, 1.24716625),
    float2(0.03772099, 2.69920026)
};
#endif
