"""Bake two periodic Bridson Poisson-disk point tables for the paint shaders.

Run from the project root: python Tools/generate_paint_poisson.py
Only PaintPoissonPoints.hlsl is generated; edit rendering code in PaintPoissonDisk.hlsl.
Reference: https://www.cs.ubc.ca/~rbridson/docs/bridson-siggraph07-poissondisk.pdf
The toroidal distance check also enforces minimum separation across tile edges.
"""
import math
from pathlib import Path
import random

PERIOD = 4.0
MIN_DISTANCE = 0.8

def distance_squared(a, b):
    d = [min(abs(x-y), PERIOD-abs(x-y)) for x,y in zip(a,b)]
    return sum(x*x for x in d)

def generate(seed):
    rng = random.Random(seed)
    points = [(rng.random()*PERIOD, rng.random()*PERIOD)]
    active = [0]
    while active:
        index = rng.choice(active)
        for _ in range(30):
            angle = rng.random()*math.tau
            radius = MIN_DISTANCE*math.sqrt(1+3*rng.random())
            p = tuple((points[index][i]+radius*f(angle)) % PERIOD
                      for i,f in enumerate((math.cos,math.sin)))
            if all(distance_squared(p,q) >= MIN_DISTANCE**2 for q in points):
                points.append(p)
                active.append(len(points)-1)
                break
        else:
            active.remove(index)
    return points

def build():
    sets = [generate(1729), generate(9473)]
    declarations = []
    for i,points in enumerate(sets):
        # Validate the rounded coordinates that will actually reach the GPU.
        rounded = [tuple(round(v,8) for v in p) for p in points]
        minimum = min(math.sqrt(distance_squared(a,b)) for j,a in enumerate(rounded) for b in rounded[j+1:])
        assert minimum >= MIN_DISTANCE
        print(f'Layer {i+1}: {len(points)} points, minimum toroidal separation {minimum:.6f}')
        values = ',\n'.join(f'    float2({x:.8f}, {y:.8f})' for x,y in points)
        declarations.append(f'#define PAINT_POISSON_SET{i}_SIZE {len(points)}\nstatic const float2 PaintPoissonPoints{i}[{len(points)}] = {{\n{values}\n}};')
    source = '''// Generated by Tools/generate_paint_poisson.py. Do not edit the point tables.
// Two periodic Bridson sets: period 4, minimum separation 0.8 in density-scaled UV.
#ifndef PAINT_POISSON_POINTS_INCLUDED
#define PAINT_POISSON_POINTS_INCLUDED
'''+ '\n\n'.join(declarations)+'\n#endif\n'
    output = Path(__file__).resolve().parents[1] / 'Assets/Shaders/PaintPoissonPoints.hlsl'
    output.write_text(source, encoding='utf-8')
    return sets

if __name__ == '__main__':
    build()
